version: '3.8'

services:
  mnist-serving:
    build: .
    container_name: mnist-serving
    ports:
      - "8500:8500"  # gRPC
      - "8501:8501"  # REST API
    volumes:
      - ./models:/models
      - ./monitoring.config:/models/monitoring.config
    environment:
      - MODEL_NAME=mnist_model
      - MODEL_BASE_PATH=/models/mnist_model
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/v1/models/mnist_model"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus:latest
    container_name: mnist-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped

networks:
  default:
    name: mnist-serving-network
