FROM python:3.11-slim
WORKDIR /app
COPY requirements.frontend.txt ./
RUN pip install --no-cache-dir -r requirements.frontend.txt
COPY app.py templates ./
ENV TF_HOST=http://tfserving:8501
ENV MODEL_NAME=simple_classifier
EXPOSE 5002

COPY . .  


CMD ["python", "app.py"]
